# This is fully copy pasted and adapted, as recommended by docsy website
baseURL = 'https://localhost:1313/'
languageCode = 'en-us'
title = 'External Secrets'

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[taxonomies]
tag = "tags"
category = "categories"

[mediaTypes."text/redirects"]
delimiter = ""

[outputFormats.redirects]
baseName = "_redirects"
isPlainText = true
mediaType = "text/redirects"
root = true

[permalinks]
blog = "/:section/:year/:month/:day/:slugorcontentbasename"

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[languages.en]
languageName = "English"

[languages.en.params]
description = "Documentation website for ESO and other projects"

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "tango"
noClasses = false

[outputs]
home = [ "HTML", "print", "RSS", "JSON", "redirects" ]
section = [ "HTML", "print", "RSS" ]

[params]
#privacy_policy = "https://policies.google.com/privacy"
# Sentinel value for per-project version dropdowns
# The actual version lists are in data/eso_versions.toml and data/reloader_versions.toml
versions = [{ version = "", url = "" }]
github_repo = "https://github.com/evrardj-roche/external-secrets-website"
github_project_repo = "https://github.com/evrardj-roche/external-secrets"
github_reloader_repo = "https://github.com/evrardj-roche/reloader"
github_branch = "main"
#gcs_engine_id = "d72aa9b2712488cc3"
#offlineSearch = false
offlineSearch = true
prism_syntax_highlighting = false
mainBranchPreviewURL = "https://main--goldydocs.netlify.app/"
btn-lg = 'class="btn btn-lg btn-{1}" role="button"'
FA = '<i class="fa-{1} fa-{2} text-{3} px-1"></i>'

[params.taxonomy]
taxonomyCloud = [ "tags", "categories" ]
taxonomyCloudTitle = [ "Tag Cloud", "Categories" ]
taxonomyPageHeader = [ "tags", "categories" ]

[params.copyright]
authors = """External-Secrets Authors"""
#"""
#[Apache 2.0](http://www.apache.org/licenses/) <br />
#The Linux Foundation has registered trademarks and uses trademarks.
#For a list of trademarks of The Linux Foundation, please see our [Trademark Usage page](https://www.linuxfoundation.org/trademark-usage/).
#"""
from_year = 2020
to_year = "present"

[params.ui]
breadcrumb_disable = false
navbar_logo = true
navbar_translucent_over_cover_disable = false
sidebar_menu_foldable = true
sidebar_menu_compact = false
sidebar_search_disable = false
showLightDarkModeMenu = true
sidebar_root_enabled = true

  [params.ui.feedback]
  enable = true
  yes = 'Glad to hear it! Please <a href="https://github.com/evrardj-roche/external-secrets-website/issues/new">tell us how we can improve</a>.'
  no = 'Sorry to hear that. Please <a href="https://github.com/evrardj-roche/external-secrets-website/issues/new">tell us how we can improve</a>.'

  [params.ui.readingtime]
  enable = true
  #enable = false

#[[params.links.user]]
#name = "User mailing list"
#url = "https://example.org/mail"
#icon = "fa fa-envelope"
#desc = "Discussion and help from your fellow users"

[[params.links.user]]
name = "X"
url = "https://twitter.com/ExtSecretsOptr"
icon = "fab fa-x-twitter"
desc = "Follow us on X to get the latest news!"

#[[params.links.developer]]
#name = "Site info"
#url = "/site/"
#icon = "fa-solid fa-hammer"
#desc = "Site build information."

[[params.links.developer]]
name = "GitHub"
url = "https://github.com/evrardj-roche/external-secrets-website"
icon = "fab fa-github"
desc = "Website page source is here!"

[[params.links.developer]]
name = "Slack"
url = "https://kubernetes.slack.com/messages/external-secrets"
icon = "fab fa-slack"
desc = "Chat with other project members"

#[[params.links.developer]]
#name = "Developer mailing list"
#url = "https://example.org/mail"
#icon = "fa fa-envelope"
#desc = "Discuss development issues around the project"

[security.funcs]
getenv = [
  "^(BRANCH|BUILD_ID|COMMIT_REF|CONTEXT|DEPLOY_ID|NETLIFY|PULL_REQUEST|REVIEW_ID)$"
]


[module]
proxy = "direct"

[module.hugoVersion]
extended = true
min = "0.155.0"

[[module.imports]]
path = "github.com/google/docsy"

